### ISSUE TITLE
JitPack Build for 2.0.6 failing

### ISSUE THREAD

**Issue by dodgex** [jarlah/testcontainers-ceph#149]
As the title says, the Build on JitPack for 2.0.6 is failing.

https://jitpack.io/com/github/jarlah/testcontainers-ceph/2.0.6/build.log

Seems taht the build runs on 3.6.1....
```
Init SDKMan
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
Maven home: /opt/apache-maven-3.6.1
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-11
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.14.63-xxxx-std-ipv6-64", arch: "amd64", family: "unix"

Running: mvn clean install -DskipTests
```

but the surefire plugin requires 3.6.3?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.1:test (default-test) on project testcontainers-ceph: The plugin org.apache.maven.plugins:maven-surefire-plugin:3.3.1 requires Maven version 3.6.3 -> [Help 1]
```

**Comment by jarlah** [comment]
Vups havent been testing jitpack lately. However, it should not be needed unless forked. Or in cases where i have unpublished changes on master

**Comment by jarlah** [comment]
If you have a suggestion on how to fix it please advise with PR

**Comment by jarlah** [comment]
we should probably find a way to verify the jitpack compatibility in the github actions workflow

**Comment by dodgex** [comment]
Oh, you are right... not sure what was going on on our side then...

Our Nexus did not find the 2.0.6 and I as always I searched on mvnrepository.com for the artifactId [`testcontainers-ceph`](https://mvnrepository.com/search?q=testcontainers-ceph) and it found nothing, and on the readme i just saw "jitpack" and checked if there was a build. Which i then triggered but it failed. :)

I'll check what Problem our Nexus had. :D

---

Regarding making JitPack work, I found on thier [docs](https://docs.jitpack.io/building/#maven-projects), that they suggest using [maven wrapper](https://maven.apache.org/wrapper/) ([GitHub Repo](https://github.com/apache/maven-wrapper)) for custom maven versions.

Setup should be as easy as running `mvn wrapper:wrapper` it then creates a `mvnw` shell script and `mvnw.bat` batch file as well as an `.mvn/wrapper` folder with a properties file defining the desired version. (see for example in [spring pet-clinic demo](https://github.com/spring-projects/spring-petclinic))

**Comment by jarlah** [comment]
you can test again now with jitpack if you'd like. 

1. Updated readme to not include jetpack documentation since thats given for all public repos should be possible
2. Added maven wrapper with "newer" maven version

**Comment by dodgex** [comment]
https://jitpack.io/com/github/jarlah/testcontainers-ceph/a95211be8e/build.log

The jitpack build with maven wrapper was successful. :)
