### ISSUE TITLE
Bug in Ceph container startupStrategy

### ISSUE THREAD

**Issue by feddevanderlist** [jarlah/testcontainers-ceph#176]
Since testcontainers version 1.20.0 they have edited the `setAwaitStrategy` and the `waitFor`.
Because of this change you can no longer change the wating strategy of this container.
This strategy is set inside the `configure()` override this function is run by start and will now never be overridden.

Before 1.20.0 the `waitFor` would override but the  `setAwaitStrategy' wouldn't.

Solution:
Set the wait strategy in the constructor of your container. Instead of in the configure. This way setting a strategy after calling `new CephContainer` or `Super()` will override the waitingStrategy.

**Comment by jarlah** [comment]
@feddevanderlist version 2.0.7 will be available in maven repos in some hours. It takes awful alot of time tbh. While your waiting you can add a star to the repository (its kinda like a "please like and subscribe") :muscle:

**Comment by feddevanderlist** [comment]
Thanks for the fast fix :D
That's something you definitely have ahead of other opensource repo's.
I'll be back for some other things. I have some ideas. To make contributing more standardized and easy.
